#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

i=1
n=10
while [ "$i" -le "$n" ];
do
	echo "Best School"
	if [ "$i" -eq 9 ];then
		echo "Hi"
	fi
	((i++))
done
