#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration
# displays Best School and then Hi on a new line.
# using while loop and if statement
a=0
while [ $a -lt 10 ]
do
    if [ $a -eq 9 ];then
        echo "Hi"
    fi
    echo "Best School"
    ((a = a + 1))
done
