#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
# using while loop
hour=0
minutes=1
while [ $hour -lt 13 ]
do
    echo "Hour: "$hour
    while [ $minutes -lt 60 ]
    do
        echo "$minutes"
        ((minutes = minutes + 1))
    done
    minutes=1
    ((hour = hour + 1))
done
