#!/usr/bin/env bash
#Bash script that displays the content of the current directory
#In a list format where only the part of the name after the first dash is displayed
#Do not display hidden files
#using for loop
list=$(ls)
for a in $list
do
    echo "$a" | cut -d '-' -f2;
done
